- name: GitHub issue for all hosts
  hosts: all
  tasks:
  - name: Check if GitHub issue is closed or not
    community.general.github_issue:
      organization: ansible
      repo: ansible
      issue: 23642
      action: get_status
    register: r

  - name: Take action depending upon issue status
    ansible.builtin.debug:
      msg: Do something when issue 23642 is open
    when: r.issue_status == 'open'