---

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    source: http://192.168.49.2:32532/api/galaxy/

  - name: community.docker
    source: http://192.168.49.2:32532/api/galaxy/
